Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  # config.vm.provision "shell" do |ssh|
  #   ssh_pub_key= File.readlines("/home/bchifour/.ssh/id_rsa.pub").first.strip
  #   ssh.inline = <<-SHELL
  #   echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
  #   SHELL
  # end


  config.vm.define "Server" do |machin_1|
    machin_1.vm.hostname = "Server"
    machin_1.vm.network "private_network", ip: "192.168.56.110"
    # machin_1.vm.boot_timeout = 0
    machin_1.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
    # machin_1.vm.provision "shell" path:
  end

  config.vm.define "ServerWorker" do |machin_2|
    machin_2.vm.hostname = "ServerWorker"
    machin_2.vm.network "private_network", ip: "192.168.56.111"
    # machin_2.vm.boot_timeout = 0
    machin_2.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
    # machin_1.vm.provision "shell" path:
  end

end
