apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1-ingress
spec:
  rules:
  - host: argocd1.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: will-app-service
            port:
              number: 8888