apiVersion: v1
kind: Service
metadata:
  name: will-app-service
  labels:
    app: will
spec:
  type: LoadBalancer
  selector:
      app: will
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 8888